steps:
  # Build using Kaniko for efficient layer caching
  # Kaniko caches layers in Artifact Registry, avoiding full rebuilds
  - name: "gcr.io/kaniko-project/executor:latest"
    id: "build"
    args:
      - "--destination=${_IMAGE_URL}"
      - "--cache=true"
      - "--cache-ttl=168h"
      - "--cache-repo=${_CACHE_REPO}"
      - "--dockerfile=frontend/Dockerfile"
      - "--context=dir:///workspace/frontend"
      - "--build-arg=BUILD_ENV=${_BUILD_ENV}"
      - "--build-arg=NEXTAUTH_URL=${_NEXTAUTH_URL}"
      - "--build-arg=NEXT_PUBLIC_SITE_URL=${_NEXT_PUBLIC_SITE_URL}"
      - "--build-arg=NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}"
      - "--build-arg=NEXT_PUBLIC_SUPPORT_EMAIL=${_NEXT_PUBLIC_SUPPORT_EMAIL}"

  # Tag and push cache images in parallel for future builds
  - name: "gcr.io/cloud-builders/docker"
    id: "push-cache-deps"
    waitFor: ["build"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull ${_IMAGE_URL} && \
        docker tag ${_IMAGE_URL} ${_IMAGE_URL}-cache-deps && \
        docker push ${_IMAGE_URL}-cache-deps || true

  - name: "gcr.io/cloud-builders/docker"
    id: "push-cache-builder"
    waitFor: ["build"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull ${_IMAGE_URL} && \
        docker tag ${_IMAGE_URL} ${_IMAGE_URL}-cache-builder && \
        docker push ${_IMAGE_URL}-cache-builder || true

# Default substitutions (will be overridden by Terraform)
substitutions:
  _IMAGE_URL: "${_IMAGE_URL}"
  _BUILD_ENV: "staging"
  _CACHE_REPO: "${_IMAGE_URL}-cache"

options:
  logging: CLOUD_LOGGING_ONLY
  # Use cheaper machine type (E2_HIGHCPU_8 is 75% cheaper than E2_HIGHCPU_32)
  machineType: "E2_HIGHCPU_8"
  # Disk size for build
  diskSizeGb: 50

# Timeout for the entire build (with Kaniko caching, should complete faster)
timeout: "600s"
